version: '3'
services:
  nginx:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --email mphist@gmail.com --agree-tos --no-eff-email --staging -d kitkat.bar  -d www.kitkat.bar
  node-app:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL_DIGITALOCEAN}
    networks:
      - app-network
    command: >
      sh -c "npm run db:migrate:prod &&
             npm run build &&
             npm run start:prod"
  db:
    networks:
      - app-network
volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
