version: '3'
services:
  node-app:
    build: .
    image: mphist/s-mart-server
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
