version: '3'
services:
  node-app:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL_DIGITALOCEAN}
    command: >
      sh -c "npm run db:migrate:prod &&
             npm run build &&
             npm run start:prod"
