version: '3'
services:
  nginx:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  node-app:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL_DIGITALOCEAN}
    command: >
      sh -c "npm run db:migrate:prod &&
             npm run build &&
             npm run start:prod"
